### PR TITLE
Fix typo in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by taivlam**
Capitalize [Matrix](https://en.wikipedia.org/wiki/Matrix_(protocol))

### CODE REVIEW

**Comment by soupslurpr** [comment]
Merged already, duplicate

**Comment by taivlam** [comment]
Sorry about that, things got confusing with my browser on my end.

**Comment by soupslurpr** [comment]
It's okay :)

**Comment by taivlam** [comment]
Maybe?  I swore I had already submitted the original request, but then GitHub's web interface indicated I had commits that weren't "packaged" into a pull request in another tab.

**Pull request closed without merging**
