### PR TITLE
Add baseline and startup profiles

### PR DESCRIPTION
**Pull request by t895**
Baseline profiles help guide Android's AOT compiler by providing code paths that we're interested in getting the most performance out of. The baseline profile module creates a UIAutomator test that walks through the critical screens of the app and collects the relevant information for the compiler along the way. Google's documentation for the plugin that makes this work is [here](https://developer.android.com/topic/performance/baselineprofiles/overview).

In order to make this work properly, I had to enable `testTagsAsResourceId` for the root composable in the app (Note - If you ever want to tag something like an alert dialog, you'll need to enable that flag for the dialog specifically because it creates a new Composable heirarchy). Then, I added test tags to all of the Composables that I wanted UIAutomator to interact with. Finally, I assembled a basic test in `BaselineProfileGenerator.kt` to walk through the main screens of the app.

In order to generate a new baseline and startup profile, run `.\gradlew :app:generateReleaseBaselineProfile`.

You do not need to run this generator every time there is a change made to the app. I'd recommend you re-run this whenever a large dependency is added and the user interacts with in in one of your main screens. So in addition, you'll need to add functionality to the test in `BaselineProfileGenerator.kt`.

Also sorry for the intimidating line count. I've isolated the actual changes to my first commit since the generated profiles are so massive.

### CODE REVIEW

**Comment by soupslurpr** [comment]
Thanks, but Compose comes with a profile already so I don't think specifying our own is needed. Does this actually improve performance in places where it stutters? Maybe the predictive back animation for going back from the app list to the start screen?

**Comment by t895** [comment]
Sorry for the wait. I didn't have a good way of benchmarking until today.
With a dedicated profile, you're able to see some improvement in stuttering (166ms -> 114ms in the 99th percentile of frame overrun) and about a 7% improvement in startup time.
image

After about 3 or more launches of the app, performance will become better than the baseline profile, but it's nice to smooth out the out-of-box experience.

**Comment by soupslurpr** [comment]
Unfortunately, this would add too much effort for little gain. It isn't very useful for AppVerifier anyways since a little more speed for the first few launches isn't something that's important.

**Comment by t895** [comment]
That's fine
I appreciate your consideration

**Pull request closed without merging**
