### PR TITLE
Add Amazon Shopping app

### PR DESCRIPTION
**Pull request by sawft99**
- Added Amazon Shopping app

I wanted to start with just doing 1 first to make sure it is right before adding any more. Thanks.

### CODE REVIEW

**Comment by soupslurpr** [comment]
Hi, thanks. The comment is supposed to be the source where you got the app from. See the comment at the top of the verification info database file please and other entries for examples. Also check if its available on other stores or sites and if so check if they are the same hashes. If they aren't the same hashes and its the same package name then you have to add it in another "Hashes" in the same InternalDatabaseVerificationInfo

**Comment by sawft99** [comment]
Got it. I updated to have the correct source name. At first glance I thought the source was equal to the app name. I saw I could download the apk direct from Amazon's [site](https://www.amazon.com/gp/mas/blp/install). I'm not a real developer by any means and I am even less familiar with how Android works under the hood so pardon what might be a dumb question. 

When grabbing the apk for Amazon sites directly, am I simply getting the file hash of the apk or something else?

**Comment by soupslurpr** [comment]
When you open the apk with AppVerifier, its the same as opening the entry for an installed app. Its just more secure as you can verify before installing and not after. So no its not the hash of the apk file but rather the hash of the signing certificate(s).

**Review by soupslurpr — APPROVED** [review]
Cross-verification succeeded, thank you.

**Comment by sawft99** [comment]
Thanks. I have a long list id like to contribute. Would one large pull request be fine or should i do one change per pull request?

**Comment by soupslurpr** [comment]
One large pull request would be harder to review, ideally could you do one pull request for each app?

**Comment by sawft99** [comment]
Sure i figured it would be so wanted to check

**Comment by sawft99** [comment]
Oh, this hadn't been merged yet. Added Paypal. I'll wait for the merge.

**Comment by soupslurpr** [comment]
@sawft99 you're supposed to make a new branch from master and not use master so you can have multiple pull requests at the same time and keep an unmodified master

**Comment by soupslurpr** [comment]
I'd recommend doing that instead of using master, so save these changes and delete your fork, then fork again and make a new branch for each app. Thanks.

**Pull request closed without merging**
