### PR TITLE
Add 37 more unique app signature hashes

### PR DESCRIPTION
**Pull request by life00**
I extracted signatures hashes from most of my current apps and made sure there is no duplicates submitted. I also correctly formatted everything using regex. In the future I will likely contribute more app signature hashes.

Now it is necessary to verify the listed signature hashes and optionally add signature hashes for apps from other sources. Afterwards it is ready to be merged.

### CODE REVIEW

**Comment by life00** [comment]
please only verify those app signature hashes which have comments. Those that don't are WIP

**Comment by soupslurpr** [comment]
👍 For the apps you still haven't please add the comment with GitHub/Google Play Store or Codeberg/Google Play Store or whatever combination and not Official.

**Comment by life00** [comment]
@soupslurpr completed some part of it. You may start verifying those with comments.

**Comment by soupslurpr** [comment]
Thanks, but the verification info format unfortunately had to be changed to support multiple signers and signing key rotation. Please refer to https://github.com/soupslurpr/AppVerifier/blob/master/CONTRIBUTING.md for info about how the database will be formatted. :)

**Comment by life00** [comment]
@soupslurpr but it is correct. You sent me the sample. It is only necessary to resolve the merge conflict (shouldn't be difficult).

**Comment by life00** [comment]
however I am still working on my submission

**Comment by soupslurpr** [comment]
You did the formatting wrong, there should be a Hashes for every different list of hashes

**Comment by life00** [comment]
ok I will redo everything again

**Comment by soupslurpr** [comment]
sorry, I should have explained it clearer

**Comment by soupslurpr** [comment]
There is an explanation at the top in the comment and also refer to the previous entries.

**Comment by life00** [comment]
yeah you should've sent two hash entries. I also don't know how to resolve all of these merge conflicts (and sync fork) cuz I never actually contributed properly :laughing:

**Pull request closed without merging**
