### PR TITLE
Add org.fossify.calendar app.

### PR DESCRIPTION
**Pull request by rufusprice**
Add org.fossify.calendar

### CODE REVIEW

**Comment by felschr** [comment]
I've verified all 3 sources: Google Play Store, GitHub release & F-Droid.
Additionally I checked that the IzzyOnDroid release which distributes the APK from GitHub is also identical.

```
org.fossify.calendar
AF:FD:B1:24:D3:F4:72:0C:2F:98:DB:CA:9E:AC:BA:05:14:FB:A4:30:6E:20:A2:78:6C:86:1C:3C:0D:6F:F2:92
```

**Comment by felschr** [comment]
I noticed you've introduced a merge commit d27493261796e1b55d749fa7a2daf20602b1ecba which isn't necessary. Not sure if soupslurpr has the same opinion on this, but merge requests should probably be rebased when there are conflicts instead of the merged.

Just as a side note: It seems that other Fossify apps use the same hash. At least Fossify Gallery does.

**Comment by soupslurpr** [comment]
> I noticed you've introduced a merge commit [d274932](https://github.com/soupslurpr/AppVerifier/commit/d27493261796e1b55d749fa7a2daf20602b1ecba) which isn't necessary. Not sure if soupslurpr has the same opinion on this, but merge requests should probably be rebased when there are conflicts instead of the merged.

Yeah, @rufusprice please remove the merge commit.

**Comment by rufusprice** [comment]
created a new one here https://github.com/soupslurpr/AppVerifier/pull/151

**Pull request closed without merging**
