### PR TITLE
Add basic search

### LINKED ISSUE #48: Add search functionality
I have a lot of apps and it is kinda difficult to find the app I am interested in right away. I suggest to add some kind of search functionality for app names or package names.

### PR DESCRIPTION
**Pull request by felschr**
Closes #48

I'm not really an Android or Kotlin dev, so this probably needs some clean up but I kinda got a search bar implemented.
It uses an experimental Material 3 API, not sure if that's a deal-breaker for you.

### CODE REVIEW

**Comment by soupslurpr** [comment]
Thanks, one problem I see is that it seems to only filter with the package name, and not the name of the app. I think it should give results from searching both the package name and the name at the same time. If you'd like I can continue off from here and finish it myself! I had no idea Compose had an experimental search bar component 😆

**Comment by soupslurpr** [comment]
Also it should be attached to the top of the screen always instead of going away when scrolling down, perhaps adding a top bar or just moving it out of the LazyColumn.

**Comment by felschr** [comment]
I've just added an icon, a placeholder & made it sticky.
I've adopted a `Scaffold` which already takes care of the spacing for the OS's navigation bar, so I removed the extra `Spacer`.

Here is what it looks like:

appverifier-search

**Comment by soupslurpr** [comment]
Thanks, just made a few minor adjustments like moving the searchQuery to AppVerifier.kt and in rememberSaveable to save its state on configuration changes (rotating, changing size, etc), fixing edge-to-edge by adjusting LazyColumn innerPadding to not include the bottom padding (edge-to-edge is when it is immersive, the bottom padding for the navigation bar is removed and the spacer was for adding a navigation bar at the bottom of the app list so that there aren't any unreachable entries (especially happens when using the old 3 button navigation)), and clearing searchQuery when going back to StartupScreen.

**Comment by soupslurpr** [comment]
merged in https://github.com/soupslurpr/AppVerifier/commit/12c9b1b58c3d2ee4e67728ec2081da920c4f1d4e

**Comment by soupslurpr** [comment]
Oops I messed up when merging it so it says it twice

**Pull request closed without merging**
